### ISSUE TITLE
Need some help to use it 

### ISSUE THREAD

**Issue by JiaoYanMoGu** [Enri2077/realtime-manifold-mesh-reconstructor#2]
Hi, I'm very interested in the program, and I want to know whether there's any document about how to use it or some videos that can show us the result. Thanks ~

**Comment by JiaruiWang-Jill** [comment]
hi, @JiaoYanMoGu , did you succeed to make it out? I am also stuck in using it.

**Comment by JiaoYanMoGu** [comment]
emmm... failed and I give up
