### ISSUE TITLE
Need openMVG dataset for test

### ISSUE THREAD

**Issue by liupengsyk** [Enri2077/realtime-manifold-mesh-reconstructor#3]
Dear Enri2077,
        I found that the sfm_data data structure for your's  is not the same as Openmvg. I tried to convert OpenMVG's sfm_data.bin into your structure, but it failed. Can you provide an openmvg data set for testing?

**Comment by luca-morreale** [comment]
Dear @liupengsyk,
thank you for your interest in this repository. I have just uploaded a json data example from KITTI dataset (sequence 95). I will soon update the main source file to let you test the code with the data I just uploaded.

**Comment by luca-morreale** [comment]
Dear @liupengsyk,
I have just updated the repository, one you have compile the source code you should launch the ```sfmReconstructor``` as follows:
```
./build/sfmReconstructor data/sfm_data.json
```
it will generate the reconstructions in the ```output``` folder.
If you do not have such folder, please create it before running ```sfmReconstructor```.

Please let me know if you have further issues. I will soon update the README file.

**Comment by liupengsyk** [comment]
Dear @Enri2077 
Thank you for your reply！ After I update the source code and recompile，and launch sfmReconstructor with  your dataset .
The program works fine, but I found that the current version did not remove the outliers, which caused the resulting triangulation to have a lot of noise.
I have two question:
1、I use " openMVG -> openMVG_main_ConvertSfM_DataFormat  " to convert sfm_data.bin (UTM 49N) to sfm_data.json, but it not work. The log as follows:

`./build/sfmReconstructor ./build/sfm_data.json ./res/config/default.json 20
input set to: ./build/sfm_data.json
config set to: ./res/config/default.json
max_iterations set to: 20
read config success!
Opening stats file res/stats/timeStats default.csv
Opening counts file res/stats/countStats default.csv
main loop						Done in 0.000162s 
main loop						Done in 0.000418s 
main loop						Done in 0.000217s 
TriangulationManager::updateTriangulation: 			 min chrono time			43 ns
TriangulationManager::initSteinerPointGridAndBound:   		 added Steiner points: 			8
TriangulationManager::initSteinerPointGridAndBound:   		 total Steiner points: 			8
TriangulationManager::initSteinerPointGridAndBound:   		 Steiner grid side lengths: 		x: 21	y: 21	z: 21
TriangulationManager::updateSteinerPointGridAndBound: 		 added Steiner points: 			19
TriangulationManager::initSteinerPointGridAndBound:   		 total Steiner points: 			27
TriangulationManager::updateSteinerPointGridAndBound: 		 Steiner grid side lengths: 		x: 41	y: 41	z: 41
initSteinerGrid		0.00268279

rayRemoving		Skipped

TriangulationManager::updateTriangulation:		 rays removed:				0	 /	0
Overall shrink		Skipped

Remove vertices		Skipped

TriangulationManager::rayTracingFromAllCam:		 vertices removed:	 -1
Remove points		Skipped

TriangulationManager::rayTracingFromAllCam:		 points removed:	 0
Add new vertices	0.000307154

Move vertices		Skipped

Move Cameras		Skipped

rayUntracing		Skipped

rayTracing		Skipped

rayRetracing		Skipped

TriangulationManager::growManifold: 		 boundary is empty, growing from the cell with highest vote
ManifoldManager::growManifold:		 no local boundary cells found, searching in all boundary
ManifoldManager::growManifold:		 no boundary cells found.
growManifold		3.334e-05

ManifoldManager::growSeveralAtOnce:			 no local boundary cells found.
growManifoldSev		1.468e-06

ManifoldManager::growManifold:		 no local boundary cells found, searching in all boundary
ManifoldManager::growManifold:		 no boundary cells found.
growManifold		3.599e-06

TriangulationManager::updateTriangulation:			 mm 	 updated cameras:		4
TriangulationManager::updateTriangulation:			 mm 	 added points:			0
TriangulationManager::updateTriangulation:			 mm 	 moved points:			0	/	377
TriangulationManager::updateTriangulation:			 mm 	 moved cameras:			0	/	0
TriangulationManager::updateTriangulation:			 mm 	 insertInBoundary:		6.178e-06 s
TriangulationManager::updateTriangulation:			 mm 	 removeFromBoundary:		0 s
TriangulationManager::updateTriangulation:			 mm 	 isRegularTest/1:			0 s
TriangulationManager::updateTriangulation:			 mm 	 isRegularTest/2:			0 s
TriangulationManager::updateTriangulation:			 mm 	 singleTest:			0 s
TriangulationManager::updateTriangulation:			 rt2	 useless:			0 s
TriangulationManager::updateTriangulation:			 rt2	 first cell:			0 s
TriangulationManager::updateTriangulation:			 rt2	 cell traversing:		0 s
TriangulationManager::updateTriangulation:			 rt2	 index cache hit ratio:		-nan
TriangulationManager::updateTriangulation:			 rt2	 neighbours weight update:	0 s	 / 	0
TriangulationManager::updateTriangulation:			 rt2	 neighbours int insert/remove:	0 s	 / 	0

updateTriangulation		0.00339301
ManifoldManager::checkBoundaryIntegrity: checking...
		 tests failed on cell:
					 !isFreespace(boundaryCell)
			 info on cell:
					 points:	-10	-24	-2	-16
		 tests failed on cell:
					 !isFreespace(boundaryCell)
			 info on cell:
					 points:	-10	-24	-2	-16
		 tests failed on cell:
					 !isFreespace(boundaryCell)
			 info on cell:
					 points:	-10	-24	-2	-16
		 tests failed on cell:
					 !isFreespace(boundaryCell)
			 info on cell:
					 points:	-10	-24	-2	-16
#                checked 4 cells
#########      Integrity Check FAILED!!!      #########

main loop						Done in 0.003914s 
main loop						Done in 0.000351s 
main loop						Done in 0.000142s 
TriangulationManager::updateTriangulation: 			 min chrono time			38 ns
TriangulationManager::updateSteinerPointGridAndBound: 		 added Steiner points: 			0
TriangulationManager::initSteinerPointGridAndBound:   		 total Steiner points: 			27
TriangulationManager::updateSteinerPointGridAndBound: 		 Steiner grid side lengths: 		x: 41	y: 41	z: 41
updateSteinerGrid		5.956e-06

rayRemoving		Skipped

TriangulationManager::updateTriangulation:		 rays removed:				0	 /	0
Overall shrink		Skipped

Remove vertices		Skipped

TriangulationManager::rayTracingFromAllCam:		 vertices removed:	 -1
Remove points		Skipped

TriangulationManager::rayTracingFromAllCam:		 points removed:	 0
Add new vertices	9.3516e-05

Move vertices		Skipped

Move Cameras		Skipped

rayUntracing		Skipped

rayTracing		Skipped

rayRetracing		Skipped

ManifoldManager::growManifold:		 no local boundary cells found, searching in all boundary
ManifoldManager::growManifold:		 no boundary cells found.
growManifold		5.904e-06

ManifoldManager::growSeveralAtOnce:			 no local boundary cells found.
growManifoldSev		1.234e-06

ManifoldManager::growManifold:		 no local boundary cells found, searching in all boundary
ManifoldManager::growManifold:		 no boundary cells found.
growManifold		3.604e-06

TriangulationManager::updateTriangulation:			 mm 	 updated cameras:		2
TriangulationManager::updateTriangulation:			 mm 	 added points:			0
TriangulationManager::updateTriangulation:			 mm 	 moved points:			0	/	592
TriangulationManager::updateTriangulation:			 mm 	 moved cameras:			0	/	0
TriangulationManager::updateTriangulation:			 mm 	 insertInBoundary:		0 s
TriangulationManager::updateTriangulation:			 mm 	 removeFromBoundary:		0 s
TriangulationManager::updateTriangulation:			 mm 	 isRegularTest/1:			0 s
TriangulationManager::updateTriangulation:			 mm 	 isRegularTest/2:			0 s
TriangulationManager::updateTriangulation:			 mm 	 singleTest:			0 s
TriangulationManager::updateTriangulation:			 rt2	 useless:			0 s
TriangulationManager::updateTriangulation:			 rt2	 first cell:			0 s
TriangulationManager::updateTriangulation:			 rt2	 cell traversing:		0 s
TriangulationManager::updateTriangulation:			 rt2	 index cache hit ratio:		-nan
TriangulationManager::updateTriangulation:			 rt2	 neighbours weight update:	0 s	 / 	0
TriangulationManager::updateTriangulation:			 rt2	 neighbours int insert/remove:	0 s	 / 	0

updateTriangulation		0.00029003
saving output/manifold_final.off
OutputManager::writeMeshToOff	 conf_:0x223d7f0
enableIdentifiedPoints: 1
enableInverseConic: 1
enableRayMistrust: 0
enablePointsPositionUpdate: 0
enableUnusedVertexRemoving: 0
generateColoredMesh: 0
freeVoteThreshold: 20
nonConicFreeVoteThreshold: 1
rayRemovalThreshold: 100
unusedVertexRemovalThreshold: 100
primaryPointsVisibilityThreshold: 2
minDistancePointPositionUpdate: 0
maxPointsPerCamera: 1000000
maxDistanceCameraPoints: 40
steinerGridStepLength: 20
maxSteinerVerticesPerTriangle: 4
w_1: 10
w_2: 2
w_3: 1
w_m: 1
triangulationUpdateEvery: 4
initialTriangulationUpdateSkip: 2
saveMeshEvery: 10
fakePointsMultiplier: 0
timeStatsOutput: 1
debugOutput: 0
publishReceivedPointcloud: 0
publishUsedPointcloud: 0
checkIntegrityWhenFinished: 0
outputFolder: res/output/
timeStatsFolder: res/stats/
countStatsFolder: res/stats/
statsId: default

boundaryCellsSpatialMap size		 4
writeMeshToOff collect  :		0.00214187 s
writeMeshToOff write    :		5.0693e-05 s
writeMeshToOff vertices :	4
writeMeshToOff triangles:	4
writeMeshToOff avoidedSteinerVertices:	0
save manifold			0.00223103
main						Done in 3.81503s 
`
**Is this question related to UTM?**

2、Have you considered referring to the method of removing outliers in openMVS -> ReconstructMesh?

**Comment by luca-morreale** [comment]
Dear @liupengsyk,
I am happy to hear you manage to make our code work!
Regarding your issue (point 1), it might be the case you have to adjust the parameter `steinerGridStepLength` in your configuration file. Intuitively, it has to be proportional to the scene size. If you have no idea of the right scale you could try to scale it up by 10 and see if the reconstruction improves.
You can also do the same to `maxDistanceCamFeature`.

About point 2, we have not yet. It is a good suggestion though, thanks!

**Comment by SPengLiang** [comment]
I want to download the sfm_data,what should I do？ thank you

**Comment by SPengLiang** [comment]
Inside OpenMvgParser::parse()， document_.Parse(str.c_str())，and the str is "version https://gitlfs.github.com/spec/v1
oid sha256:26a4381a3bd7c39b7157d9759d603e5662916b65c52828651d6d42c47ce7b587
size 144161886" ,after Parse() ,document_.HasMember("intrinsics") is false

**Comment by SPengLiang** [comment]
I already got it, thank you
