### ISSUE TITLE
I got all false inliers after outlierFiltering

### ISSUE THREAD

**Issue by SPengLiang** [Enri2077/realtime-manifold-mesh-reconstructor#4]
thank you advance, I run the Main_sfm.cpp file using the sfm_data,but when outlierFiltering,  GaussNewton returns all -1

**Comment by luca-morreale** [comment]
Dear @SPengLiang,
sorry for the late reply!
I think the problem might be in the threshold used to filter the outliers.
You can find it here:
https://github.com/Enri2077/realtime-manifold-mesh-reconstructor/blob/6e2a6af32711cc459c3e7c542aaccae8ad63a36c/res/config/default.json#L14

Try to tune that parameter, it should solve your problem!
