### ISSUE TITLE
the json file  is not valid

### ISSUE THREAD

**Issue by emphos1** [Enri2077/realtime-manifold-mesh-reconstructor#5]
Hi @luca-morreale, I managed to make the project successfully. However, when I tried to test the code, I got this error. Could you please have a look at the following lines? Thanks.

input:
./build/sfmReconstructor data/sfm_data.json

output:
input set to: data/sfm_data.json
config set to: res/config/default.json
max_iterations set to: 0
JsonParseException--> the json file  is not valid
JsonParseException--> the json file  is not valid
JsonAccessException--> error while querying HasMember(views)
JsonAccessException--> error while querying HasMember(views)
JsonAccessException--> error while querying HasMember(extrinsics)
JsonAccessException--> error while querying HasMember(extrinsics)
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)

**Comment by buqing2009** [comment]
@emphos1 I have the same problem, do you solve it ?
