### ISSUE TITLE
How to visualize the incremental reconstruction process

### ISSUE THREAD

**Issue by VirtualRooom** [Enri2077/realtime-manifold-mesh-reconstructor#7]
Thank you for sharing the source. I have successfully run the program and got a series of .off files. But I want to see the reconstruction process, is there any way to visualize the incremental reconstruction process in this video?
[https://www.youtube.com/watch?v=VaLx6Klz13Y&ab_channel=ICRA2018](url)

**Comment by Enri2077** [comment]
Hi,
I don't think we had a code for the animation and it's been a very long time so I don't remember exactly how we did the animation at the end of the video.
But the mesh is saved every n iterations and the origin stays the same, so I guess you could just switch from one mesh to the next and put the camera of the animation in the same pose as the camera from the input.
